### ISSUE TITLE
App runs fine via Python, but runs many versions in PyInstaller edition

### ISSUE THREAD

**Issue by mikeckennedy** [chriskiehl/Gooey#252]
Hi there,

I'm working on a project to demo this app and use cookiecutter to build scaffolding for Pyramid web apps. You can see the whole (simple) thing here:

https://github.com/mikeckennedy/pyramid-web-builder-python-gui

When I run this via:

`python3 program.py`

It works perfectly! Lovin' Gooey. But, if I package it in PyInstaller, it also runs, but does something crazy. When I press start, another UI copy is launched. I exit that, and still another UI app copy is launched. Upon cancelling these two extra apps, the primary app succeeds but the output is basically missing.

Any idea what I'm missing? This happens on macOS and Windows (feel free to try from the github repo above). Is this a known issue?

Thank you!

**Comment by mikeckennedy** [comment]
Here's a screenshot of my Gooey inception.

<img width="719" alt="screen shot 2018-02-06 at 9 59 14 pm" src="https://user-images.githubusercontent.com/2035561/35901056-bbfa83ec-0b89-11e8-9161-5b3b2933a358.png">

**Comment by mikeckennedy** [comment]
For some reason, this does not happen on Linux but does on macOS and Windows. I have created Gooey apps that do not have this problem when packaged via PyInstaller. Let me know if you see why this particular app is doing this.

**Comment by chriskiehl** [comment]
Need some more info: 

OS/Python version/Gooey version/virtual env[yes/no]/minimal code example reproducing the issue/spec file/ version of pyinstaller/packaging steps used / anything else you think may be useful

**Comment by mikeckennedy** [comment]
Hi @chriskiehl thanks for looking at this. Here's some info:

OS: macOS 10.13.3 (latest High Sierra patched)
OS 2: Windows 10 (latest, everything else the same)
Python version: 3.6.4
Gooey version: 1.0.0 
PyInstaller: 3.3.1
virtual env[yes/no]: **yes**
minimal code example: A very basic version didn't have this problem. So I'm not sure what is simpler than what's listed here that recreates it. This code is pretty simple:

https://github.com/mikeckennedy/pyramid-web-builder-python-gui/tree/master/app

Just `program.py`, ignore the `bootstrapper.py` thing.

Remember, after setting up the VENV, 

**this works fine**: `python program.py`
**this fails**: `pyinstaller build.spec`, then `./dist/MY_APP`

Want a short screencast of the problem?

**Comment by chriskiehl** [comment]
Hm.. I recall encountering this in the past, but it was one of those things that magically resolved itself at the time. 

There's something funky with the shell. I can't reproduce your issue with stock Gooey. However, if swap the Shell arguments in `processor.py` to `False`, suddenly I can reproduce your issue after packaging everything with PyInstaller. 

Out of curiosity, do you use a custom default shell on Windows? 

```
echo %COMSPEC%
```

Does that point to `cmd.exe`? 

Additionally, would you mind spelunking around Gooey's internals and swapping lines [49](https://github.com/chriskiehl/Gooey/blob/master/gooey/gui/processor.py#L49) and [54](https://github.com/chriskiehl/Gooey/blob/master/gooey/gui/processor.py#L54) to `shell=False`. Give it a packaging and see if that works? 

I'm still digging in, but if your default shell is different, or if the above changes make any kind of difference after packaging, that'll be useful in pinning down the root cause of all this.

**Comment by chriskiehl** [comment]
Hey @mikeckennedy,

So you don't have to muck about with the Gooey internals, I've pushed a branch here that allows you to configure `shell=true|false` from the Gooey decorator (which, after reading the docs again, it seems like I merge it into the main project, as 90% of the time it should probably be set to `False` anyway...) 

Branch is here: 
```
pip install git+https://github.com/chriskiehl/Gooey@debug-shell
```

You can shut off the shell by passing `False` to the Gooey Decorator

```
@Gooey(requires_shell=False)
def main(): 
   ...rest of code 
```

**Comment by mikeckennedy** [comment]
Hi Chris,

Thanks for this! Having that option seems good. It did seem to fix an issue with showing the terminal with the app when using PyInstaller. However, it didn't seem to fix the inception issue.

Also, when setting requires_shell=False in macOS, there is an error running the app (outside of Pyinstaller's version, just `python app.py`). Basically it couldn't restart itself:

```python
'/Users/mkennedy/github/mk/pyramid-web-builder-python-gui/.env/bin/python' -u 'program.py' --ignore-gooey -- 'Starter' 'jjuu' 'chameleon' '/Users/mkennedy/Desktop/n'
Traceback (most recent call last):
  File "/Users/mkennedy/github/mk/pyramid-web-builder-python-gui/.env/lib/python3.6/site-packages/gooey/gui/processor.py", line 50, in run
    stderr=subprocess.STDOUT, shell=self.shell_execution, env=env)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: b"'/Users/mkennedy/github/mk/pyramid-web-builder-python-gui/.env/bin/python' -u 'program.py' --ignore-gooey -- 'Starter' 'jjuu' 'chameleon' '/Users/mkennedy/Desktop/n'": b"'/Users/mkennedy/github/mk/pyramid-web-builder-python-gui/.env/bin/python' -u 'program.py' --ignore-gooey -- 'Starter' 'jjuu' 'chameleon' '/Users/mkennedy/Desktop/n'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mkennedy/github/mk/pyramid-web-builder-python-gui/.env/lib/python3.6/site-packages/wx/core.py", line 3190, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/Users/mkennedy/github/mk/pyramid-web-builder-python-gui/.env/lib/python3.6/site-packages/gooey/gui/containers/application.py", line 80, in onStart
    self.clientRunner.run(self.buildCliString())
  File "/Users/mkennedy/github/mk/pyramid-web-builder-python-gui/.env/lib/python3.6/site-packages/gooey/gui/processor.py", line 55, in run
    stderr=subprocess.STDOUT, shell=self.shell_execution, env=env)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: "'/Users/mkennedy/github/mk/pyramid-web-builder-python-gui/.env/bin/python' -u 'program.py' --ignore-gooey -- 'Starter' 'jjuu' 'chameleon' '/Users/mkennedy/Desktop/n'": "'/Users/mkennedy/github/mk/pyramid-web-builder-python-gui/.env/bin/python' -u 'program.py' --ignore-gooey -- 'Starter' 'jjuu' 'chameleon' '/Users/mkennedy/Desktop/n'"
```

**Comment by mikeckennedy** [comment]
This was using a Python 3.6.4 virtual environment.

**Comment by mikeckennedy** [comment]
Actually, the platform Python3 has the same outcome:

```python
'/Library/Frameworks/Python.framework/Versions/3.6/bin/python3' -u 'program.py' --ignore-gooey -- 'Starter' 'uuvccz' 'chameleon' '/Users/mkennedy/Desktop/n'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gooey/gui/processor.py", line 50, in run
    stderr=subprocess.STDOUT, shell=self.shell_execution, env=env)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: b"'/Library/Frameworks/Python.framework/Versions/3.6/bin/python3' -u 'program.py' --ignore-gooey -- 'Starter' 'uuvccz' 'chameleon' '/Users/mkennedy/Desktop/n'": b"'/Library/Frameworks/Python.framework/Versions/3.6/bin/python3' -u 'program.py' --ignore-gooey -- 'Starter' 'uuvccz' 'chameleon' '/Users/mkennedy/Desktop/n'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wx/core.py", line 3190, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gooey/gui/containers/application.py", line 80, in onStart
    self.clientRunner.run(self.buildCliString())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gooey/gui/processor.py", line 55, in run
    stderr=subprocess.STDOUT, shell=self.shell_execution, env=env)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: "'/Library/Frameworks/Python.framework/Versions/3.6/bin/python3' -u 'program.py' --ignore-gooey -- 'Starter' 'uuvccz' 'chameleon' '/Users/mkennedy/Desktop/n'": "'/Library/Frameworks/Python.framework/Versions/3.6/bin/python3' -u 'program.py' --ignore-gooey -- 'Starter' 'uuvccz' 'chameleon' '/Users/mkennedy/Desktop/n'"
```

**Comment by iamkroot** [comment]
Facing the exact same issue on Windows. And I do use a custom shell (cmder), but `%comspec%` still says `cmd`. Adding `requires_shell=False` doesn't help either, still getting new instances when pressing start in the pyinstaller version. Anything else I can try @chriskiehl?

**Comment by iamkroot** [comment]
Found the source of the bug. The problem was that I was using multiprocessing, but didn't use [`freeze_support()`](http://docs.python.org/library/multiprocessing.html#multiprocessing.freeze_support) as [required](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing) by pyinstaller. This resulted in an extra call to the built exe *without* `--ignore-gooey` when the main app tried to start the process. And hence the inception.

Adding a `multiprocessing.freeze_support()` call before main has solved the issue. @mikeckennedy your bug may also be due to the same thing.

**Comment by chriskiehl** [comment]
@iamkroot Awesome debugging! Glad you were able to resolve it. 

I'm not sure if that's @mikeckennedy issue, unfortunately. I took a quick poke around the repo he originally linked by didn't see any reference to the `multiprocessing` library.  : (

**Comment by mikeckennedy** [comment]
Hi @chriskiehl Yeah, bummer it's not the same issue. :)

**Comment by ericpace** [comment]
Hi Chris,

Having the same issue as @mikeckennedy, however this problem is occurring even without packaging with PyInstaller (happens in when debugging in PyCharm).

For some reason earlier iterations of the project were not causing this. i am trying to determine what I may have inadvertently changed.

My setup:
OS: macOS 10.14.6
Python version: 3.7.1
Gooey version: 1.0.3
PyCharm: 2018.2.5
Virtual Env: yes created by PyCharm

Thanks Chris!

**Comment by ericpace** [comment]
So I created a new project, and started building up from a MWE. My project works fine up until the point where I introduce `__init__.py` and point it to my `__main__.py` as follows:
`
from my_project.__main__ import (
  main,
)
`

My testing has been as follows:

1. Running `__main__.py` from PyCharm fails with the inception bug (once I introduce `__init__.py`. It works find prior to this)
2. Deploying to PyPi, installing the project via pip on Windows with a GUI entry point, fails with the inception bug
3. Deploying to PyPi, installing the project via pip on MacOS with a GUI entry point, works

For reference, the project I am working on is https://github.com/ericpace/dicom_anon_tool and may be installed with pip using `pip install dicom_anonymiser` which should also install Gooey.
